config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#home"

  get 'invitations', to: 'dashboard#invitation'
  get 'accept_invitation', to: 'dashboard#accept_invitation'
  get 'reject_invitation', to: 'dashboard#reject_invitation'

  resources :events do
  	resources :invitations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	validates :name, :description, :start_time, :end_time, presence: true

	has_many :invitations, dependent: :destroy
	belongs_to :user

	def associated_invitation
		invitations.where(event_id: id).last
	end

	def event_duration
		time_diff = end_time - start_time
		if (time_diff / 1.hour) > 1
			"#{(time_diff / 1.hour)} Hrs"
		else
			"#{(time_diff / 1.minute)} Minutes"
		end
	end

end

app/models/invitation.rb
class Invitation < ApplicationRecord

	include AASM

	validates :email, presence: true
	validate :validate_invitation_email, on: :create

	belongs_to :event

	scope :not_accepted, -> { where.not(status: 'accepted') }

	aasm do
		state :pending, initial: true
		state :accepted, :rejected

		event :accept do
      transitions from: [:pending, :rejected], to: :accepted, after: Proc.new { accept_invitation }
    end

    event :reject do
      transitions from: [:pending, :accepted], to: :rejected, after: Proc.new { reject_invitation }
    end
  end

	private

	def validate_invitation_email
		unless User.all.pluck(:email).include?(email)
			errors.add(:base, 'User with this email does not exist')
		end
	end

	def accept_invitation
		update_column(:status, 'accepted')
	end

	def reject_invitation
		update_column(:status, 'rejected')
	end

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :require_login

	def home
		@events = Event.joins(:invitations)
			.where('invitations.email' => current_user.email, 'invitations.status' => 'accepted')
	end

	def invitation
		@invitations = Invitation.where(email: current_user.email).not_accepted.reload
	end

	def accept_invitation
		Invitation.find(params[:id]).accept!
		redirect_to invitations_path
	end

	def reject_invitation
		Invitation.find(params[:id]).reject!
		redirect_to invitations_path
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :require_login
  before_action :set_event, only: [:edit, :update, :show, :destroy]

	def index
		@events = current_user.reload.events.paginate(page: params[:page], per_page: 5)
	end

	def new
		@event = current_user.events.new
	end

	def create
    @event = current_user.events.new(event_params)
    if @event.save
      flash[:success] = "Event was successfully created"
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event was successfully updated"
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    flash[:danger] = "Event was successfully deleted"
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_time, :end_time)
  end

  def set_event
    @event = Event.find(params[:id])  
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
	before_action :require_login
	before_action :find_event
	before_action :validate_user_email, only: [:create]
	before_action :validate_redundant_invitation, only: [:create]

	def new
		@invitation = @event.invitations.new
	end

	def create
		@invitation = @event.invitations.new(invitation_params)
    if @invitation.save
      flash[:success] = "Invitation was sent successfully"
      redirect_to event_path(@event)
    else
      render 'new'
    end
	end

	private

	def invitation_params
    params.require(:invitation).permit(:email)
  end

	def find_event
		@event = Event.find(params[:event_id]).reload
	end

	def validate_user_email
    if params[:invitation][:email] == current_user.email
      flash[:danger] = "You cannot send invitation to self"
      redirect_to event_path(@event)
    end
  end

  def validate_redundant_invitation
  	if @event.invitations.pluck(:email).include?(params[:invitation][:email])
  		flash[:danger] = "You have already sent invitation to this User"
  		redirect_to event_path(@event)
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def conditional_link(args)
    if !args[:disabled]
      return link_to args[:string], args[:url], class: args[:klass]
    else 
      return args[:string]
    end
  end
end

app/views/dashboard/home.html.erb
<h1>Events to be attended</h1>
<%= calendar(events: @events, number_of_days: 1) do |date, events| %>
  <%= date %>
  <hr>
  <% events.each do |event| %>
    <div>
      <strong>Name: </strong><%= event.name %>
    </div>
    <div>
      <strong>Duration: </strong><%= event.event_duration %>
    </div>
    <div>
    	<%= link_to "Reject", reject_invitation_path(id: event.associated_invitation.id), class: "btn btn-xs btn-danger" %>
    </div>
    <hr>
  <% end %>

<% end %>

app/views/dashboard/invitation.html.erb
<h1 align="center">Listing all Invitation</h1>
<% @invitations.each do |invitation| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="event-title">
          <strong>Name: </strong><%= invitation.event.name %>
        </div>
        <div class=".event-description">
          <strong>Description: </strong><%= truncate(invitation.event.description, length: 100) %>
        </div>
        <div>
          <strong>Status: </strong><%= invitation.status %>
        </div>
        <hr>
        <%= link_to "Accept", accept_invitation_path(id: invitation.id), class: "btn btn-xs btn-success" %>
        <%= conditional_link({
          disabled: invitation.rejected?,
          string: "Reject", 
          url: reject_invitation_path(id: invitation.id),
          klass: "btn btn-xs btn-danger"
        }) %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= render 'shared/errors', obj: @event %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@event, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of event", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of event" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :start_time %>
        </div>
        <div class="col-sm-8">
          <%= f.datetime_select  :start_time, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :end_time %>
        </div>
        <div class="col-sm-8">
          <%= f.datetime_select  :end_time, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to event listing", events_path %> ]
    </div>
  </div>
</div>
    

app/views/events/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1 align="center">Listing all Events</h1>
<div align="right">
  <%= link_to "Add new event", new_event_path, class: "btn btn-xs btn-warning" %>
</div>
<div align="center">
  <%= will_paginate %>
</div>
<% @events.each do |event| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="event-title">
          <%= event.name %>
        </div>
        <div class=".event-description">
          <%= truncate(event.description, length: 100) %>
        </div>
        <% if signed_in? %>
          <div class="event-actions">
            <%= link_to "Edit this event", edit_event_path(event), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this event", event_path(event), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete the event?"}, 
                                          class: "btn btn-xs btn-danger" %>
            <%= link_to "Show this event", event_path(event), class: "btn btn-xs btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/events/new.html.erb
<h1 align="center">Create an event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h2 align="center">Title: <%= @event.name %></h2>
<div align="right">
  <%= link_to "Invite User", new_event_invitation_path(event_id: @event.id), class: "btn btn-xs btn-warning" %>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@event.description) %>
  <div class="event-actions">
    <% if signed_in? %>
      <%= link_to "Edit this event", edit_event_path(@event), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this event", event_path(@event), method: :delete, 
                                        data: { confirm: "Are you sure you want to delete the event?"}, 
                                        class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all events", events_path, class: "btn btn-xs btn-success" %>
  </div>
  <hr>
  <h4 class="center description">Invited Users:</h4>
  <% @event.reload.invitations.each do |invitation| %>
    <div class="well well-lg">
      <%= invitation.email %>
    </div>
  <% end %>
</div>

app/views/invitations/new.html.erb
<%= render 'shared/errors', obj: @invitation %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@invitation, url: event_invitations_path(event_id: @event.id), :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :email, class: "form-control", placeholder: "Email of user", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Send Invitation', class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to event", event_path(@event) %> ]
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="navbar-brand">
    <% if signed_in? %>
      <%= link_to 'Dashboard', root_path %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if signed_in? %>
          <%= link_to 'My Events', events_path %>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if signed_in? %>
          <%= link_to 'Invited Events', invitations_path %>
        <% end %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li><%= link_to 'Log out', sign_out_path, method: :delete %></li>
      <% else %>
        <li class="btn btn-outline-success my-2 my-sm-0 mr-1">
          <%= link_to 'Log in', sign_in_path %>
        </li>
        <li class="btn btn-outline-danger my-2 my-sm-0">
          <%= link_to 'Sign up', sign_up_path %>    
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEventApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class.to_s %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container-fluid">
  <%= form_for @user do |form| %>
    <div class="form-group col-md-8">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email', class: 'form-control' %>
    </div>
    <div class="form-group col-md-8">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group col-md-8">
      <%= form.submit class: 'btn btn-success' %>
    </div>
  <% end %>
</div>